### ISSUE TITLE
PR #5 didn't actually got merged

### ISSUE THREAD

**Issue by kuc2477** [theverytak/readingHBR#6]
Looks like PR #5 didn't actually got merged into your master branch. Check out the commit history. Github's PR tab says it has been merged but [actual commit log says it hasn't](https://github.com/theverytak/readingHBR/commits/master)

**Comment by theverytak** [comment]
Yes, it does. Can I rewind it?

**Comment by kuc2477** [comment]
I reopened PR #5 in master branch. Merging PR #7 should work.
